apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret_ghrc.name }}
  namespace: task5-5
type: {{ .Values.secret_ghrc.type }}
data:
  .dockerconfigjson: {{ .Values.secret_ghrc.githubToken }}
