# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/aldans/kbot.git
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.0.3-bc9cd1c"
  arch: linux-arm64
  
service:  
  ports:
  - port: 8080

secret:
  name: kbot
  tokenName: TELE_TOKEN
  tokenKey: key
  
secret_tele:
  name: kbot
  botToken: # Your bot token
  
secret_ghrc:
  name: github-registry-secret
  type: kubernetes.io/dockerconfigjson
  githubToken: # Your github registry token

imagePullSecrets:
  name: github-registry-secret
